service:
  name: client-service

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource: arn:aws:sqs:${file(./config.js):region}:${file(./config.js):accountId}:${file(./config.js):queueName}

functions:
  sender:
    handler: handler.sender
    events:
      - http:
          method: post
          path: send
